// Debredamo Hotel - Site Configuration

import type { Locale } from '@/types';

export const siteConfig = {
  name: {
    en: 'Debredamo Hotel',
    am: 'ደብረዳሞ ሆቴል',
  },
  description: {
    en: 'Experience luxury and comfort in the heart of Addis Ababa. Debredamo Hotel offers premium accommodation, exceptional service, and authentic Ethiopian hospitality.',
    am: 'በአዲስ አበባ ልብ ውስጥ ቅንጦትና ምቾትን ይለማመዱ። ደብረዳሞ ሆቴል ከፍተኛ መኖሪያ፣ ልዩ አገልግሎት እና ትክክለኛ የኢትዮጵያ እንግዳ መስተንግዶን ይሰጣል።',
  },
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  ogImage: '/images/og-image.jpg',
  links: {
    facebook: '',
    instagram: '',
    twitter: '',
    whatsapp: '+251911123456',
  },
  contact: {
    email: 'reservations@debredamohotel.com',
    phone: '+251-11-123-4567',
    address: {
      street: '123 Main Street',
      city: 'Addis Ababa',
      country: 'Ethiopia',
    },
  },
  defaultLocale: 'en' as Locale,
  locales: ['en', 'am'] as Locale[],
};

export const roomTypes = [
  { value: 'standard', label: { en: 'Standard Room', am: 'መደበኛ ክፍል' } },
  { value: 'deluxe', label: { en: 'Deluxe Room', am: 'ልዩ ክፍል' } },
  { value: 'executive', label: { en: 'Executive Suite', am: 'ስራ አስፈፃሚ ስዊት' } },
  { value: 'presidential', label: { en: 'Presidential Suite', am: 'የፕሬዚዳንት ስዊት' } },
] as const;

export const reservationStatuses = [
  { value: 'pending', label: { en: 'Pending', am: 'በመጠባበቅ ላይ' }, color: 'yellow' },
  { value: 'contacted', label: { en: 'Contacted', am: 'ተገናኝቷል' }, color: 'blue' },
  { value: 'confirmed', label: { en: 'Confirmed', am: 'ተረጋግጧል' }, color: 'green' },
  { value: 'declined', label: { en: 'Declined', am: 'ተቃውሟል' }, color: 'red' },
  { value: 'cancelled', label: { en: 'Cancelled', am: 'ተሰርዟል' }, color: 'gray' },
] as const;

export const amenitiesIcons: Record<string, string> = {
  'Free WiFi': 'wifi',
  'Air Conditioning': 'wind',
  'TV': 'tv',
  'Mini Bar': 'wine',
  'Mini Fridge': 'refrigerator',
  'Safe': 'lock',
  'Work Desk': 'laptop',
  'Sitting Area': 'armchair',
  'Bathtub': 'bath',
  'Private Bathroom': 'shower',
  'Complimentary Toiletries': 'sparkles',
  'Daily Housekeeping': 'broom',
  '24/7 Room Service': 'room-service',
  'City View': 'building',
  'Balcony': 'door-open',
  'Kitchen': 'chef-hat',
  'Nespresso Machine': 'coffee',
  'Bathrobes & Slippers': 'shirt',
  'Premium Toiletries': 'sparkles',
  'Jacuzzi': 'waves',
  'Smart TV': 'tv',
  'Flat-screen TV': 'monitor',
};

export const services = [
  {
    icon: 'utensils',
    title: { en: 'Restaurant & Dining', am: 'ምግብ ቤት' },
    description: {
      en: 'Enjoy authentic Ethiopian and international cuisine',
      am: 'ትክክለኛ የኢትዮጵያ እና ዓለም አቀፍ ምግብ ይደሰቱ',
    },
  },
  {
    icon: 'wine',
    title: { en: 'Bar & Lounge', am: 'ባር እና መዝናኛ' },
    description: {
      en: 'Relax with premium drinks and cocktails',
      am: 'ከፍተኛ መጠጦችና ኮክቴሎች ይዝናኑ',
    },
  },
  {
    icon: 'briefcase',
    title: { en: 'Business Center', am: 'የንግድ ማእከል' },
    description: {
      en: 'Fully equipped meeting rooms and facilities',
      am: 'ሙሉ በሙሉ የተዘጋጁ የስብሰባ ክፍሎች',
    },
  },
  {
    icon: 'concierge',
    title: { en: 'Concierge Service', am: 'የኮንሲየርጅ አገልግሎት' },
    description: {
      en: 'Personal assistance for all your needs',
      am: 'ለሁሉም ፍላጎቶችዎ ግላዊ እርዳታ',
    },
  },
  {
    icon: 'wifi',
    title: { en: 'Free WiFi', am: 'ነፃ ዋይፋይ' },
    description: {
      en: 'High-speed internet throughout the hotel',
      am: 'በሆቴል ውስጥ ፈጣን ኢንተርኔት',
    },
  },
  {
    icon: 'car',
    title: { en: 'Parking', am: 'የመኪና ማቆሚያ' },
    description: {
      en: 'Secure parking for hotel guests',
      am: 'ለሆቴል እንግዶች ደህንነቱ የተጠበቀ ማቆሚያ',
    },
  },
];

// Room Data
export const rooms = [
  {
    id: '1',
    name: 'Standard Room',
    name_am: 'መደበኛ ክፍል',
    slug: 'standard-room',
    description: 'Our Standard Rooms offer comfort and convenience for the modern traveler. Each room features a comfortable queen-size bed, modern amenities, and a cozy atmosphere perfect for both business and leisure stays. The room is designed with warm tones and elegant furnishings to create a welcoming environment. Large windows provide natural light and views of the city. The private bathroom includes a rainfall shower and complimentary premium toiletries.',
    description_am: 'መደበኛ ክፍሎቻችን ለዘመናዊው ተጓዥ ምቾትና ቀላልነት ይሰጣሉ። እያንዳንዱ ክፍል ምቹ የንግስት መጠን አልጋ፣ ዘመናዊ መገልገያዎች፣ እና ለንግድም ሆነ ለመዝናኛ ቆይታ ፍጹም የሆነ ምቹ ሁኔታ አለው።',
    room_type: 'standard',
    size_sqm: 28,
    max_guests: 2,
    base_price_etb: 2500,
    images: [
      { url: '/images/rooms/standard-1.jpg', alt: 'Standard room with queen bed' },
      { url: '/images/rooms/standard-2.jpg', alt: 'Standard room bathroom' },
      { url: '/images/rooms/standard-3.jpg', alt: 'Standard room workspace' },
    ],
    amenities: [
      'Free WiFi',
      'Air Conditioning',
      'Flat-screen TV',
      'Mini Fridge',
      'Safe',
      'Work Desk',
      'Private Bathroom',
      'Complimentary Toiletries',
      'Daily Housekeeping',
      '24/7 Room Service',
    ],
    is_active: true,
    display_order: 1,
  },
  {
    id: '2',
    name: 'Deluxe Room',
    name_am: 'ልዩ ክፍል',
    slug: 'deluxe-room',
    description: 'Experience enhanced comfort in our Deluxe Rooms. Spacious and elegantly designed, these rooms feature premium bedding, a sitting area, and upgraded amenities for a luxurious stay. Perfect for guests who appreciate refined comfort and style. The room includes a separate seating area, ideal for relaxation or informal meetings. Floor-to-ceiling windows offer stunning city views. The spacious bathroom features a deep soaking tub and separate rain shower.',
    description_am: 'ልዩ ክፍሎቻችን ውስጥ የተሻሻለ ምቾት ይለማመዱ። ሰፊና በውበት የተቀየሰ፣ እነዚህ ክፍሎች ከፍተኛ የአልጋ ዝግጅት፣ መቀመጫ ቦታ፣ እና ለቅንጦት ቆይታ የተሻሻሉ መገልገያዎች አሏቸው።',
    room_type: 'deluxe',
    size_sqm: 35,
    max_guests: 2,
    base_price_etb: 3500,
    images: [
      { url: '/images/rooms/deluxe-1.jpg', alt: 'Deluxe room with king bed' },
      { url: '/images/rooms/deluxe-2.jpg', alt: 'Deluxe room sitting area' },
      { url: '/images/rooms/deluxe-3.jpg', alt: 'Deluxe room bathroom with bathtub' },
    ],
    amenities: [
      'Free WiFi',
      'Air Conditioning',
      '55-inch Smart TV',
      'Mini Bar',
      'Safe',
      'Work Desk',
      'Sitting Area',
      'Bathtub',
      'Premium Toiletries',
      'Bathrobes & Slippers',
      'Nespresso Machine',
      'Daily Housekeeping',
      '24/7 Room Service',
      'City View',
    ],
    is_active: true,
    display_order: 2,
  },
  {
    id: '3',
    name: 'Executive Suite',
    name_am: 'ስራ አስፈፃሚ ስዊት',
    slug: 'executive-suite',
    description: 'Our Executive Suites combine elegance with functionality. Perfect for business travelers, these suites feature a separate living area, executive workspace, and premium amenities. The spacious layout includes a dedicated work area with ergonomic seating and high-speed connectivity. The living room is ideal for private meetings or relaxation. Enjoy access to our executive lounge with complimentary refreshments. The luxurious bathroom features a jacuzzi tub and premium bath products.',
    description_am: 'ስራ አስፈፃሚ ስዊቶቻችን ውበትን ከተግባራዊነት ጋር ያዋህዳሉ። ለንግድ ተጓዦች ፍጹም፣ እነዚህ ስዊቶች የተለየ የመኖሪያ ቦታ፣ የስራ አስፈፃሚ የስራ ቦታ እና ከፍተኛ መገልገያዎች አሏቸው።',
    room_type: 'executive',
    size_sqm: 45,
    max_guests: 3,
    base_price_etb: 5000,
    images: [
      { url: '/images/rooms/executive-1.jpg', alt: 'Executive suite living area' },
      { url: '/images/rooms/executive-2.jpg', alt: 'Executive suite bedroom' },
      { url: '/images/rooms/executive-3.jpg', alt: 'Executive suite workspace' },
      { url: '/images/rooms/executive-4.jpg', alt: 'Executive suite bathroom' },
    ],
    amenities: [
      'Free WiFi',
      'Air Conditioning',
      '65-inch Smart TV',
      'Full Mini Bar',
      'Safe',
      'Executive Desk',
      'Separate Living Room',
      'Dining Table',
      'Jacuzzi',
      'Premium Toiletries',
      'Bathrobes & Slippers',
      'Nespresso Machine',
      'Complimentary Breakfast',
      'Daily Housekeeping',
      '24/7 Room Service',
      'City View',
      'Balcony',
    ],
    is_active: true,
    display_order: 3,
  },
  {
    id: '4',
    name: 'Presidential Suite',
    name_am: 'የፕሬዚዳንት ስዊት',
    slug: 'presidential-suite',
    description: 'The ultimate in luxury and space. Our Presidential Suite offers unparalleled comfort with a master bedroom, spacious living area, dining room, and premium amenities throughout. This exceptional suite spans 80 square meters and features two bedrooms, a formal dining area that seats six, and a fully equipped kitchen. The master bedroom includes a king-size bed and luxurious en-suite bathroom with dual vanities, jacuzzi, and steam shower. Enjoy personalized butler service and exclusive access to our VIP lounge. Perfect for extended stays or entertaining guests in style.',
    description_am: 'በቅንጦትና በቦታ ውስጥ የመጨረሻው። የእኛ የፕሬዚዳንት ስዊት ዋና መኝታ ቤት፣ ሰፊ የመኖሪያ ቦታ፣ የመመገቢያ ክፍል እና በሙሉ ከፍተኛ መገልገያዎች ያለው ተመጣጣኝ ምቾት ይሰጣል።',
    room_type: 'presidential',
    size_sqm: 80,
    max_guests: 4,
    base_price_etb: 8500,
    images: [
      { url: '/images/rooms/presidential-1.jpg', alt: 'Presidential suite entrance' },
      { url: '/images/rooms/presidential-2.jpg', alt: 'Presidential suite living room' },
      { url: '/images/rooms/presidential-3.jpg', alt: 'Presidential suite master bedroom' },
      { url: '/images/rooms/presidential-4.jpg', alt: 'Presidential suite dining area' },
      { url: '/images/rooms/presidential-5.jpg', alt: 'Presidential suite bathroom' },
    ],
    amenities: [
      'Free WiFi',
      'Air Conditioning',
      'Multiple Smart TVs',
      'Full Bar',
      'Safe',
      'Executive Office',
      'Separate Living Room',
      'Formal Dining Area',
      'Master Bedroom',
      'Guest Bedroom',
      'Kitchen',
      'Jacuzzi & Steam Shower',
      'Premium Toiletries',
      'Bathrobes & Slippers',
      'Nespresso & Tea Station',
      'Complimentary Breakfast',
      'Butler Service',
      'Daily Housekeeping',
      '24/7 Room Service',
      'Panoramic City View',
      'Large Balcony',
      'Priority Check-in/out',
    ],
    is_active: true,
    display_order: 4,
  },
] as const;
