// DEBREDAMO HOTEL - Site Configuration

import type { Locale } from "@/types";

export const siteConfig = {
  name: {
    en: "DEBREDAMO HOTEL",
    am: "ደብረዳሞ ሆቴል",
  },
  description: {
    en: "Experience luxury and comfort in the heart of Addis Ababa. DEBREDAMO HOTEL offers premium accommodation, exceptional service, and authentic Ethiopian hospitality.",
    am: "በአዲስ አበባ ልብ ውስጥ ቅንጦትና ምቾትን ይለማመዱ። ደብረዳሞ ሆቴል ከፍተኛ መኖሪያ፣ ልዩ አገልግሎት እና ትክክለኛ የኢትዮጵያ እንግዳ መስተንግዶን ይሰጣል።",
  },
  url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  ogImage: "/images/og-image.jpg",
  links: {
    facebook: "",
    instagram: "",
    twitter: "",
    whatsapp: "+251911123456",
  },
  contact: {
    email: "reservation@debredamohotel.com",
    phone: "+251116612630",
    address: {
      street: "Haile Gebre Silase St",
      city: "Addis Ababa",
      country: "Ethiopia",
    },
  },
  defaultLocale: "en" as Locale,
  locales: ["en", "am"] as Locale[],
};

export const roomTypes = [
  { value: "standard", label: { en: "Standard Room", am: "መደበኛ ክፍል" } },
  { value: "deluxe", label: { en: "Deluxe Room", am: "ልዩ ክፍል" } },
  { value: "executive", label: { en: "Executive Suite", am: "ስራ አስፈፃሚ ስዊት" } },
  {
    value: "presidential",
    label: { en: "Presidential Suite", am: "የፕሬዚዳንት ስዊት" },
  },
] as const;


export const amenitiesIcons: Record<string, string> = {
  "Free WiFi": "wifi",
  "Free High-Speed WiFi": "wifi",
  "Air Conditioning": "wind",
  TV: "tv",
  "Satellite TV": "tv",
  "Mini Bar": "wine",
  "Mini Fridge": "refrigerator",
  Safe: "lock",
  "Electronic safe": "lock",
  "Work Desk": "laptop",
  "Sitting Area": "armchair",
  "Seating Area": "armchair",
  Bathtub: "bath",
  "Private Bathroom": "shower",
  "Complimentary Toiletries": "sparkles",
  "Daily Housekeeping": "broom",
  "24/7 Room Service": "room-service",
  "City View": "building",
  "Panoramic City View": "building",
  Balcony: "door-open",
  Kitchen: "chef-hat",
  "Nespresso Machine": "coffee",
  "Bathrobes & Slippers": "shirt",
  "Premium Toiletries": "sparkles",
  Jacuzzi: "waves",
  "Smart TV": "tv",
  "Multiple Smart TVs": "tv",
  "Flat-screen TV": "monitor",
  "Separate Living Room": "sofa",
  "Dining Area": "utensils",
  "Office Workspace": "briefcase",
  "Multiple Rooms": "door-open",
  "Private Lounge Area": "armchair",
};

export const services = [
  {
    icon: "utensils",
    title: { en: "Restaurant & Dining", am: "ምግብ ቤት" },
    description: {
      en: "Enjoy authentic Ethiopian and international cuisine",
      am: "ትክክለኛ የኢትዮጵያ እና ዓለም አቀፍ ምግብ ይደሰቱ",
    },
  },
  {
    icon: "wine",
    title: { en: "Bar & Lounge", am: "ባር እና መዝናኛ" },
    description: {
      en: "Relax with premium drinks and cocktails",
      am: "ከፍተኛ መጠጦችና ኮክቴሎች ይዝናኑ",
    },
  },
  {
    icon: "briefcase",
    title: { en: "Business Center", am: "የንግድ ማእከል" },
    description: {
      en: "Fully equipped meeting rooms and facilities",
      am: "ሙሉ በሙሉ የተዘጋጁ የስብሰባ ክፍሎች",
    },
  },
  {
    icon: "concierge",
    title: { en: "Concierge Service", am: "የኮንሲየርጅ አገልግሎት" },
    description: {
      en: "Personal assistance for all your needs",
      am: "ለሁሉም ፍላጎቶችዎ ግላዊ እርዳታ",
    },
  },
  {
    icon: "wifi",
    title: { en: "Free WiFi", am: "ነፃ ዋይፋይ" },
    description: {
      en: "High-speed internet throughout the hotel",
      am: "በሆቴል ውስጥ ፈጣን ኢንተርኔት",
    },
  },
  {
    icon: "car",
    title: { en: "Parking", am: "የመኪና ማቆሚያ" },
    description: {
      en: "Secure parking for hotel guests",
      am: "ለሆቴል እንግዶች ደህንነቱ የተጠበቀ ማቆሚያ",
    },
  },
];

// Room Data
export const rooms = [
  {
    id: "1",
    name: "Single Room",
    name_am: "ነጠላ ክፍል",
    slug: "single-room",
    description:
      "A comfortable and functional room ideal for solo travelers. Featuring a single bed, modern amenities, and everything you need for a pleasant stay. Perfect for business travelers or those seeking a cozy, private space.",
    description_am:
      "ለነጠላ ተጓዦች ምቹ እና ተግባራዊ ክፍል። አንድ ነጠላ አልጋ፣ ዘመናዊ መገልገያዎች እና ለተመቻቸ ቆይታ የሚያስፈልጉ ሁሉ ነገሮች አሉት።",
    room_type: "standard",
    size_sqm: null,
    max_guests: 1,
    base_price_etb: 1800,
    images: [
      { url: "/images/Standard Room/image.png", alt: "Standard room with queen bed" },
      { url: "/images/Standard Room/612A7208.JPG", alt: "Single room workspace" },
      { url: "/images/Standard Room/612A7220.JPG", alt: "Single room" },
    ],
    amenities: [
      "Air Conditioning",
      "Free WiFi",
      "Satellite TV",
      "Mini Fridge",
      "Electronic safe",
      "Work Desk",
      "Private Bathroom",
      "Complimentary Toiletries",
      "Daily Housekeeping",
    ],
    is_active: true,
    display_order: 1,
  },
  {
    id: "2",
    name: "Standard Room",
    name_am: "መደበኛ ክፍል",
    slug: "standard-room",
    description:
      "A well-appointed room offering comfort and convenience for short or long stays. Features a queen or double bed, modern amenities, and optional city views in selected rooms. Perfect for couples or solo travelers seeking extra space.",
    description_am:
      "ለአጭር ወይም ለረጅም ጊዜ ቆይታ ምቾትና ምቾት የሚሰጥ በጥሩ ሁኔታ የተዘጋጀ ክፍል። የንግስት ወይም ድርብ አልጋ፣ ዘመናዊ መገልገያዎች እና በተመረጡ ክፍሎች ውስጥ የከተማ እይታ አለው።",
    room_type: "standard",
    size_sqm: null,
    max_guests: 2,
    base_price_etb: 2500,
    images: [
      { url: "/images/Standard Room/612A7200.JPG", alt: "Standard room seating area" },
      { url: "/images/Standard Room/612A7208.JPG", alt: "Standard room workspace" },
      { url: "/images/Standard Room/612A7220.JPG", alt: "Standard room bathroom" },
    ],
    amenities: [
      "Air Conditioning",
      "Free WiFi",
      "Satellite TV",
      "Mini Fridge",
      "Electronic safe",
      "Work Desk",
      "Private Bathroom",
      "Complimentary Toiletries",
      "Daily Housekeeping",
      "City View",
    ],
    is_active: true,
    display_order: 2,
  },
  {
    id: "3",
    name: "Twin Room",
    name_am: "ትዊን ክፍል",
    slug: "twin-room",
    description:
      "Designed for guests traveling together, featuring two separate single beds. Ideal for friends, colleagues, or family members who prefer individual sleeping arrangements while sharing the same room.",
    description_am:
      "በጋራ ለሚጓዙ እንግዶች የተነደፈ፣ ሁለት የተለዩ ነጠላ አልጋዎች ያሉት። ለጓደኞች፣ ለስራ ባልደረቦች ወይም አንድ ክፍል በሚጋሩበት ጊዜ የተለየ የመኝታ ዝግጅት ለሚፈልጉ የቤተሰብ አባላት ተስማሚ ነው።",
    room_type: "standard",
    size_sqm: null,
    max_guests: 2,
    base_price_etb: 2500,
    images: [
      { url: "/images/Twin bed/612A7167.JPG", alt: "Twin room with two single beds" },
      { url: "/images/Twin bed/612A7168.JPG", alt: "Twin room seating area" },
      { url: "/images/Twin bed/612A7178.JPG", alt: "Twin room workspace" },
      { url: "/images/Twin bed/612A7182.JPG", alt: "Twin room bathroom" },
      { url: "/images/Twin bed/612A7184.JPG", alt: "Twin room city view" },
      { url: "/images/Twin bed/612A7187.JPG", alt: "Twin room amenities" },
    ],
    amenities: [
      "Air Conditioning",
      "Free WiFi",
      "Satellite TV",
      "Mini Fridge",
      "Electronic safe",
      "Work Desk",
      "Private Bathroom",
      "Complimentary Toiletries",
      "Daily Housekeeping",
    ],
    is_active: true,
    display_order: 3,
  },
  {
    id: "4",
    name: "Deluxe Room",
    name_am: "ዴሉክስ ክፍል",
    slug: "deluxe-room",
    description:
      "A spacious room with upgraded comfort and a more refined interior. Features a king or queen bed, seating area, and enhanced city views. Perfect for guests who appreciate extra space and premium amenities.",
    description_am:
      "የተሻሻለ ምቾት እና የበለጠ የተጣራ ውስጣዊ አቀማመጥ ያለው ሰፊ ክፍል። የንጉስ ወይም የንግስት አልጋ፣ የመቀመጫ ቦታ እና የተሻሻለ የከተማ እይታ አለው።",
    room_type: "deluxe",
    size_sqm: null,
    max_guests: 2,
    base_price_etb: 3500,
    images: [
      { url: "/images/Delux room/IMG_7111.JPG", alt: "Deluxe room with king bed" },
      { url: "/images/Delux room/IMG_7115.JPG", alt: "Deluxe room seating area" },
      { url: "/images/Delux room/IMG_7130.JPG", alt: "Deluxe room workspace" },
      { url: "/images/Delux room/IMG_7133.JPG", alt: "Deluxe room bathroom" },
      { url: "/images/Delux room/IMG_7152.JPG", alt: "Deluxe room amenities" },
      { url: "/images/Delux room/IMG_7155.JPG", alt: "Deluxe room city view" },
      { url: "/images/Delux room/IMG_7160.JPG", alt: "Deluxe room details" },
      { url: "/images/Delux room/IMG_7161.JPG", alt: "Deluxe room premium features" },
    ],
    amenities: [
      "Air Conditioning",
      "Free High-Speed WiFi",
      "Satellite TV",
      "Mini Bar",
      "Electronic safe",
      "Seating Area",
      "Private Bathroom",
      "Premium Toiletries",
      "Bathrobes & Slippers",
      "Daily Housekeeping",
      "City View",
    ],
    is_active: true,
    display_order: 4,
  },
  {
    id: "5",
    name: "Damo Suite",
    name_am: "ዳሞ ስዊት",
    slug: "damo-suite",
    description:
      "An elegant suite offering separate living and sleeping areas for extended stays or business travelers. Features a king bed, spacious living room with dining area, and premium amenities throughout. Perfect for guests who need extra space for work or relaxation.",
    description_am:
      "ለረጅም ጊዜ ቆይታ ወይም ለንግድ ተጓዦች የተለየ የመኖሪያ እና የመኝታ ቦታዎች የሚሰጥ ዋና ስዊት። የንጉስ አልጋ፣ ሰፊ የመኖሪያ ክፍል ከመመገቢያ ቦታ ጋር እና በሙሉ ከፍተኛ መገልገያዎች አሉት።",
    room_type: "executive",
    size_sqm: null,
    max_guests: 2,
    base_price_etb: 5000,
    images: [
      { url: "/images/Damo Suit/612A7228.JPG", alt: "Damo Suite living room" },
      { url: "/images/Damo Suit/612A7231.JPG", alt: "Damo Suite bedroom" },
      { url: "/images/Damo Suit/612A7234.JPG", alt: "Damo Suite seating area" },
      { url: "/images/Damo Suit/612A7238.JPG", alt: "Damo Suite dining area" },
      { url: "/images/Damo Suit/612A7246.JPG", alt: "Damo Suite bathroom" },
      { url: "/images/Damo Suit/612A7253.JPG", alt: "Damo Suite workspace" },
      { url: "/images/Damo Suit/612A7259.JPG", alt: "Damo Suite amenities" },
      { url: "/images/Damo Suit/IMG_7124.JPG", alt: "Damo Suite city view" },
    ],
    amenities: [
      "Separate Living Room",
      "Air Conditioning",
      "Free High-Speed WiFi",
      "Satellite TV",
      "Mini Bar",
      "Electronic safe",
      "Dining Area",
      "Private Bathroom",
      "Premium Toiletries",
      "Bathrobes & Slippers",
      "Daily Housekeeping",
      "City View",
    ],
    is_active: true,
    display_order: 5,
  },
  {
    id: "6",
    name: "Presidential Room",
    name_am: "የፕሬዚዳንት ክፍል",
    slug: "presidential-room",
    description:
      "The most luxurious accommodation in the hotel, designed for VIP guests and executives. Features multiple rooms, a king bed, private lounge area, office workspace, and panoramic city views. Includes premium amenities and personalized service for an unforgettable stay.",
    description_am:
      "በሆቴል ውስጥ በጣም ቅንጦተኛ መኖሪያ፣ ለቪአይፒ እንግዶች እና ስራ አስፈፃሚዎች የተነደፈ። በርካታ ክፍሎች፣ የንጉስ አልጋ፣ የግል ዝምታ ቦታ፣ የቢሮ ስራ ቦታ እና የፓኖራማ የከተማ እይታ አለው።",
    room_type: "presidential",
    size_sqm: null,
    max_guests: 2,
    base_price_etb: 8500,
    images: [
      { url: "/images/presendential suit/612A0374.JPG", alt: "Presidential Suite lounge area" },
      { url: "/images/presendential suit/612A0375.JPG", alt: "Presidential Suite living room" },
      { url: "/images/presendential suit/612A0380.JPG", alt: "Presidential Suite bedroom" },
      { url: "/images/presendential suit/612A0388.JPG", alt: "Presidential Suite office workspace" },
      { url: "/images/presendential suit/612A0391.JPG", alt: "Presidential Suite dining area" },
      { url: "/images/presendential suit/612A0398.JPG", alt: "Presidential Suite bathroom" },
      { url: "/images/presendential suit/612A0403.JPG", alt: "Presidential Suite premium amenities" },
      { url: "/images/presendential suit/612A0409.JPG", alt: "Presidential Suite city view" },
      { url: "/images/presendential suit/612A0418.JPG", alt: "Presidential Suite details" },
      { url: "/images/presendential suit/612A0425.JPG", alt: "Presidential Suite luxury features" },
      { url: "/images/presendential suit/612A0439.JPG", alt: "Presidential Suite seating" },
      { url: "/images/presendential suit/612A0444.JPG", alt: "Presidential Suite panoramic view" },
      { url: "/images/presendential suit/612A0458.JPG", alt: "Presidential Suite entertainment" },
      { url: "/images/presendential suit/612A0489.JPG", alt: "Presidential Suite complete view" },
    ],
    amenities: [
      "Multiple Rooms",
      "Private Lounge Area",
      "Air Conditioning",
      "Free High-Speed WiFi",
      "Satellite TV",
      "Mini Bar",
      "Electronic safe",
      "Office Workspace",
      "Private Bathroom",
      "Premium Toiletries",
      "Bathrobes & Slippers",
      "Daily Housekeeping",
      "Panoramic City View",
    ],
    is_active: true,
    display_order: 6,
  },
] as const;
